#pragma once

#define v4_from             glms_vec4
#define v4_copy3          glms_vec4_copy3
#define v4_copy           glms_vec4_copy
#define v4_ucopy          glms_vec4_ucopy
#define v4_pack           glms_vec4_pack
#define v4_unpack         glms_vec4_unpack
#define v4_dot            glms_vec4_dot
#define v4_norm2          glms_vec4_norm2
#define v4_norm           glms_vec4_norm
#define v4_norm_one       glms_vec4_norm_one
#define v4_norm_inf       glms_vec4_norm_inf
#define v4_add            glms_vec4_add
#define v4_adds           glms_vec4_adds
#define v4_sub            glms_vec4_sub
#define v4_subs           glms_vec4_subs
#define v4_mul            glms_vec4_mul
#define v4_scale          glms_vec4_scale
#define v4_scale_as       glms_vec4_scale_as
#define v4_div            glms_vec4_div
#define v4_divs           glms_vec4_divs
#define v4_addadd         glms_vec4_addadd
#define v4_subadd         glms_vec4_subadd
#define v4_muladd         glms_vec4_muladd
#define v4_muladds        glms_vec4_muladds
#define v4_maxadd         glms_vec4_maxadd
#define v4_minadd         glms_vec4_minadd
#define v4_negate         glms_vec4_negate
#define v4_inv            glms_vec4_inv
#define v4_normalize      glms_vec4_normalize
#define v4_distance       glms_vec4_distance
#define v4_distance2      glms_vec4_distance2
#define v4_maxv           glms_vec4_maxv
#define v4_minv           glms_vec4_minv
#define v4_clamp          glms_vec4_clamp
#define v4_lerp           glms_vec4_lerp
#define v4_lerpc          glms_vec4_lerpc
#define v4_mix            glms_vec4_mix
#define v4_mixc           glms_vec4_mixc
#define v4_step_uni       glms_vec4_step_uni
#define v4_step           glms_vec4_step
#define v4_smoothstep_uni glms_vec4_smoothstep_uni
#define v4_smoothstep     glms_vec4_smoothstep
#define v4_smoothinterp   glms_vec4_smoothinterp
#define v4_smoothinterpc  glms_vec4_smoothinterpc
#define v4_cubic          glms_vec4_cubic
#define v4_swizzle        glms_vec4_swizzle

#define v4_broadcast      glms_vec4_broadcast
#define v4_fill           glms_vec4_fill
#define v4_eq             glms_vec4_eq
#define v4_eq_eps         glms_vec4_eq_eps
#define v4_eq_all         glms_vec4_eq_all
#define v4_eqv            glms_vec4_eqv
#define v4_eqv_eps        glms_vec4_eqv_eps
#define v4_max            glms_vec4_max
#define v4_min            glms_vec4_min
#define v4_isnan          glms_vec4_isnan
#define v4_isinf          glms_vec4_isinf
#define v4_isvalid        glms_vec4_isvalid
#define v4_sign           glms_vec4_sign
#define v4_abs            glms_vec4_abs
#define v4_fract          glms_vec4_fract
#define v4_hadd           glms_vec4_hadd
#define v4_sqrt           glms_vec4_sqrt

#define v2_from             glms_vec2
#define v2_pack           glms_vec2_pack
#define v2_unpack         glms_vec2_unpack
#define v2_zero           glms_vec2_zero
#define v2_one            glms_vec2_one
#define v2_dot            glms_vec2_dot
#define v2_cross          glms_vec2_cross
#define v2_norm2          glms_vec2_norm2
#define v2_norm           glms_vec2_norm
#define v2_add            glms_vec2_add
#define v2_adds           glms_vec2_adds
#define v2_sub            glms_vec2_sub
#define v2_subs           glms_vec2_subs
#define v2_mul            glms_vec2_mul
#define v2_scale          glms_vec2_scale
#define v2_scale_as       glms_vec2_scale_as
#define v2_div            glms_vec2_div
#define v2_divs           glms_vec2_divs
#define v2_addadd         glms_vec2_addadd
#define v2_subadd         glms_vec2_subadd
#define v2_muladd         glms_vec2_muladd
#define v2_muladds        glms_vec2_muladds
#define v2_maxadd         glms_vec2_maxadd
#define v2_minadd         glms_vec2_minadd
#define v2_negate         glms_vec2_negate
#define v2_normalize      glms_vec2_normalize
#define v2_rotate         glms_vec2_rotate
#define v2_distance       glms_vec2_distance
#define v2_distance2      glms_vec2_distance2
#define v2_maxv           glms_vec2_maxv
#define v2_minv           glms_vec2_minv
#define v2_clamp          glms_vec2_clamp
#define v2_lerp           glms_vec2_lerp

#define v2_fill           glms_vec2_fill
#define v2_eq             glms_vec2_eq
#define v2_eq_eps         glms_vec2_eq_eps
#define v2_eq_all         glms_vec2_eq_all
#define v2_eqv            glms_vec2_eqv
#define v2_eqv_eps        glms_vec2_eqv_eps
#define v2_max            glms_vec2_max
#define v2_min            glms_vec2_min
#define v2_isnan          glms_vec2_isnan
#define v2_isinf          glms_vec2_isinf
#define v2_isvalid        glms_vec2_isvalid
#define v2_sign           glms_vec2_sign
#define v2_sqrt           glms_vec2_sqrt

#define v3_from             glms_vec3
#define v3_pack           glms_vec3_pack
#define v3_unpack         glms_vec3_unpack
#define v3_zero           glms_vec3_zero
#define v3_one            glms_vec3_one
#define v3_dot            glms_vec3_dot
#define v3_norm2          glms_vec3_norm2
#define v3_norm           glms_vec3_norm
#define v3_norm_one       glms_vec3_norm_one
#define v3_norm_inf       glms_vec3_norm_inf
#define v3_add            glms_vec3_add
#define v3_adds           glms_vec3_adds
#define v3_sub            glms_vec3_sub
#define v3_subs           glms_vec3_subs
#define v3_mul            glms_vec3_mul
#define v3_scale          glms_vec3_scale
#define v3_scale_as       glms_vec3_scale_as
#define v3_div            glms_vec3_div
#define v3_divs           glms_vec3_divs
#define v3_addadd         glms_vec3_addadd
#define v3_subadd         glms_vec3_subadd
#define v3_muladd         glms_vec3_muladd
#define v3_muladds        glms_vec3_muladds
#define v3_maxadd         glms_vec3_maxadd
#define v3_minadd         glms_vec3_minadd
#define v3_flipsign       glms_vec3_flipsign
#define v3_negate         glms_vec3_negate
#define v3_inv            glms_vec3_inv
#define v3_normalize      glms_vec3_normalize
#define v3_cross          glms_vec3_cross
#define v3_crossn         glms_vec3_crossn
#define v3_angle          glms_vec3_angle
#define v3_rotate         glms_vec3_rotate
#define v3_rotate_m4      glms_vec3_rotate_m4
#define v3_rotate_m3      glms_vec3_rotate_m3
#define v3_proj           glms_vec3_proj
#define v3_center         glms_vec3_center
#define v3_distance       glms_vec3_distance
#define v3_distance2      glms_vec3_distance2
#define v3_maxv           glms_vec3_maxv
#define v3_minv           glms_vec3_minv
#define v3_ortho          glms_vec3_ortho
#define v3_clamp          glms_vec3_clamp
#define v3_lerp           glms_vec3_lerp
#define v3_lerpc          glms_vec3_lerpc
#define v3_mix            glms_vec3_mix
#define v3_mixc           glms_vec3_mixc
#define v3_step_uni       glms_vec3_step_uni
#define v3_step           glms_vec3_step
#define v3_smoothstep_uni glms_vec3_smoothstep_uni
#define v3_smoothstep     glms_vec3_smoothstep
#define v3_smoothinterp   glms_vec3_smoothinterp
#define v3_smoothinterpc  glms_vec3_smoothinterpc
#define v3_swizzle        glms_vec3_swizzle

#define v3_broadcast      glms_vec3_broadcast
#define v3_fill           glms_vec3_fill
#define v3_eq             glms_vec3_eq
#define v3_eq_eps         glms_vec3_eq_eps
#define v3_eq_all         glms_vec3_eq_all
#define v3_eqv            glms_vec3_eqv
#define v3_eqv_eps        glms_vec3_eqv_eps
#define v3_max            glms_vec3_max
#define v3_min            glms_vec3_min
#define v3_isnan          glms_vec3_isnan
#define v3_isinf          glms_vec3_isinf
#define v3_isvalid        glms_vec3_isvalid
#define v3_sign           glms_vec3_sign
#define v3_abs            glms_vec3_abs
#define v3_fract          glms_vec3_fract
#define v3_hadd           glms_vec3_hadd
#define v3_sqrt           glms_vec3_sqrt

#define v4i_from            glms_ivec4
#define v4i_copy          glms_ivec4_copy
#define v4i_zero          glms_ivec4_zero
#define v4i_one           glms_ivec4_one
#define v4i_add           glms_ivec4_add
#define v4i_adds          glms_ivec4_adds
#define v4i_sub           glms_ivec4_sub
#define v4i_subs          glms_ivec4_subs
#define v4i_mul           glms_ivec4_mul
#define v4i_scale         glms_ivec4_scale
#define v4i_distance2     glms_ivec4_distance2
#define v4i_distance      glms_ivec4_distance
#define v4i_maxv          glms_ivec4_maxv
#define v4i_minv          glms_ivec4_minv
#define v4i_clamp         glms_ivec4_clamp
#define v4i_abs           glms_ivec4_abs

#define v3i_from            glms_ivec3
#define v3i_copy          glms_ivec3_copy
#define v3i_zero          glms_ivec3_zero
#define v3i_one           glms_ivec3_one
#define v3i_add           glms_ivec3_add
#define v3i_adds          glms_ivec3_adds
#define v3i_sub           glms_ivec3_sub
#define v3i_subs          glms_ivec3_subs
#define v3i_mul           glms_ivec3_mul
#define v3i_scale         glms_ivec3_scale
#define v3i_distance2     glms_ivec3_distance2
#define v3i_distance      glms_ivec3_distance
#define v3i_maxv          glms_ivec3_maxv
#define v3i_minv          glms_ivec3_minv
#define v3i_clamp         glms_ivec3_clamp
#define v3i_abs           glms_ivec3_abs

#define v2i_from            glms_ivec2
#define v2i_pack          glms_ivec2_pack
#define v2i_unpack        glms_ivec2_unpack
#define v2i_zero          glms_ivec2_zero
#define v2i_one           glms_ivec2_one
#define v2i_dot           glms_ivec2_dot
#define v2i_cross         glms_ivec2_cross
#define v2i_norm2         glms_ivec2_norm2
#define v2i_norm          glms_ivec2_norm
#define v2i_add           glms_ivec2_add
#define v2i_adds          glms_ivec2_adds
#define v2i_sub           glms_ivec2_sub
#define v2i_subs          glms_ivec2_subs
#define v2i_mul           glms_ivec2_mul
#define v2i_scale         glms_ivec2_scale
#define v2i_scale_as      glms_ivec2_scale_as
#define v2i_div           glms_ivec2_div
#define v2i_divs          glms_ivec2_divs
#define v2i_addadd        glms_ivec2_addadd
#define v2i_subadd        glms_ivec2_subadd
#define v2i_muladd        glms_ivec2_muladd
#define v2i_muladds       glms_ivec2_muladds
#define v2i_maxadd        glms_ivec2_maxadd
#define v2i_minadd        glms_ivec2_minadd
#define v2i_negate        glms_ivec2_negate
#define v2i_normalize     glms_ivec2_normalize
#define v2i_rotate        glms_ivec2_rotate
#define v2i_distance      glms_ivec2_distance
#define v2i_distance2     glms_ivec2_distance2
#define v2i_maxv          glms_ivec2_maxv
#define v2i_minv          glms_ivec2_minv
#define v2i_clamp         glms_ivec2_clamp
#define v2i_lerp          glms_ivec2_lerp
#define v2i_eq            glms_ivec2_eq

#define m4_ucopy          glms_mat4_ucopy
#define m4_copy           glms_mat4_copy
#define m4_identity       glms_mat4_identity
#define m4_identity_array glms_mat4_identity_array
#define m4_zero           glms_mat4_zero
#define m4_pick3          glms_mat4_pick3
#define m4_pick3t         glms_mat4_pick3t
#define m4_ins3           glms_mat4_ins3
#define m4_mul            glms_mat4_mul
#define m4_mulN           glms_mat4_mulN
#define m4_mulv           glms_mat4_mulv
#define m4_trace          glms_mat4_trace
#define m4_trace3         glms_mat4_trace3
#define m4_quat           glms_mat4_quat
#define m4_mulv3          glms_mat4_mulv3
#define m4_transpose      glms_mat4_transpose
#define m4_scale_p        glms_mat4_scale_p
#define m4_scale          glms_mat4_scale
#define m4_det            glms_mat4_det
#define m4_inv            glms_mat4_inv
#define m4_inv_fast       glms_mat4_inv_fast
#define m4_swap_col       glms_mat4_swap_col
#define m4_swap_row       glms_mat4_swap_row
#define m4_rmc            glms_mat4_rmc

#define m4_translate glms_translate
#define m4_translate_x glms_translate_x
#define m4_translate_y glms_translate_y
#define m4_translate_z glms_translate_z
#define m4_translate_make glms_translate_make
#define m4_scale_to glms_scale_to
#define m4_scale_make glms_scale_make
#define m4_scalev glms_scale
#define m4_scale_uni glms_scale_uni
#define m4_rotate_x glms_rotate_x
#define m4_rotate_y glms_rotate_y
#define m4_rotate_z glms_rotate_z
#define m4_rotate_make glms_rotate_make
#define m4_rotate glms_rotate
#define m4_rotate_at glms_rotate_at
#define m4_rotate_atm glms_rotate_atm
#define m4_spin glms_spin
#define m4_decompose_scalev glms_decompose_scalev
#define m4_uniscaled glms_uniscaled
#define m4_decompose_rs glms_decompose_rs
#define m4_decompose glms_decompose

#define cam_frustum glms_frustum
#define cam_ortho glms_ortho
#define cam_ortho_boxi glms_ortho_boxi
#define cam_ortho_boxi_p glms_ortho_boxi_p
#define cam_ortho_boxi_pz glms_ortho_boxi_pz
#define cam_ortho_default glms_ortho_default
#define cam_ortho_default_s glms_ortho_default_s
#define cam_perspective glms_perspective
#define cam_persp_move_far glms_persp_move_far
#define cam_perspective_default glms_perspective_default
#define cam_perspective_resize glms_perspective_resize
#define cam_lookat glms_lookat
#define cam_look glms_look
#define cam_look_anyup glms_look_anyup
#define cam_persp_decomp glms_persp_decomp
#define cam_persp_decompv glms_persp_decompv
#define cam_persp_decomp_x glms_persp_decomp_x
#define cam_persp_decomp_y glms_persp_decomp_y
#define cam_persp_decomp_z glms_persp_decomp_z
#define cam_persp_decomp_far glms_persp_decomp_far
#define cam_persp_decomp_near glms_persp_decomp_near
#define cam_persp_fovy glms_persp_fovy
#define cam_persp_aspect glms_persp_aspect
#define cam_persp_sizes glms_persp_sizes


#define m3_copy           glms_mat3_copy
#define m3_identity       glms_mat3_identity
#define m3_identity_array glms_mat3_identity_array
#define m3_zero           glms_mat3_zero
#define m3_mul            glms_mat3_mul
#define m3_transpose      glms_mat3_transpose
#define m3_mulv           glms_mat3_mulv
#define m3_trace          glms_mat3_trace
#define m3_quat           glms_mat3_quat
#define m3_scale          glms_mat3_scale
#define m3_det            glms_mat3_det
#define m3_inv            glms_mat3_inv
#define m3_swap_col       glms_mat3_swap_col
#define m3_swap_row       glms_mat3_swap_row
#define m3_rmc            glms_mat3_rmc

#define m2_identity       glms_mat2_identity
#define m2_identity_array glms_mat2_identity_array
#define m2_zero           glms_mat2_zero
#define m2_mul            glms_mat2_mul
#define m2_transpose_to   glms_mat2_transpose_to
#define m2_transpose      glms_mat2_transpose
#define m2_mulv           glms_mat2_mulv
#define m2_trace          glms_mat2_trace
#define m2_scale          glms_mat2_scale
#define m2_det            glms_mat2_det
#define m2_inv            glms_mat2_inv
#define m2_swap_col       glms_mat2_swap_col
#define m2_swap_row       glms_mat2_swap_row
#define m2_rmc            glms_mat2_rmc

#define ease_linear glm_ease_linear
#define ease_sine_in glm_ease_sine_in
#define ease_sine_out glm_ease_sine_out
#define ease_sine_inout glm_ease_sine_inout
#define ease_quad_in glm_ease_quad_in
#define ease_quad_out glm_ease_quad_out
#define ease_quad_inout glm_ease_quad_inout
#define ease_cubic_in glm_ease_cubic_in
#define ease_cubic_out glm_ease_cubic_out
#define ease_cubic_inout glm_ease_cubic_inout
#define ease_quart_in glm_ease_quart_in
#define ease_quart_out glm_ease_quart_out
#define ease_quart_inout glm_ease_quart_inout

#define ease_quint_in glm_ease_quint_in
#define ease_quint_out glm_ease_quint_out
#define ease_quint_inout glm_ease_quint_inout
#define ease_exp_in glm_ease_exp_in
#define ease_exp_out glm_ease_exp_out
#define ease_exp_inout glm_ease_exp_inout
#define ease_circ_in glm_ease_circ_in
#define ease_circ_out glm_ease_circ_out
#define ease_circ_inout glm_ease_circ_inout
#define ease_back_in glm_ease_back_in
#define ease_back_out glm_ease_back_out
#define ease_back_inout glm_ease_back_inout
#define ease_elast_in glm_ease_elast_in
#define ease_elast_out glm_ease_elast_out
#define ease_elast_inout glm_ease_elast_inout
#define ease_bounce_out glm_ease_bounce_out
#define ease_bounce_in glm_ease_bounce_in
#define ease_bounce_inout glm_ease_bounce_inout
